spring:
  application:
    name: demo-provider

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    id: my-registry
  protocol:
    port: 20882
    name: dubbo
    status: server
    id: dubbo
  application:
    name: demo-provider
    id: demo-provider
    qosEnable: true
    qosPort: 22223
  scan:
    basePackages: org.hongxi.whatsmars.dubbo.demo.provider.service

endpoints:
  dubbo:
    enabled: true
management:
  port: 9091
  security:
    enabled: false

registry:
  zk:
    other: zookeeper://10.2.4.73:2181
